baseURL = "https://ragozzine.me/"

languageCode = "en-us"
title = "John Ragozzine"
theme = "ezhil"
paginate = 5

copyright = "© John Ragozzine"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-49362078-2"
disqusShortname = ""

summaryLength = 20

[params]
  Description = "Director of Agile Process at alley.co | Co-host of twoscrumsup.com podcast | Certified Scrum Master (CSM) | Project Management Professional (PMP) | I like birds."
	subtitle = "Scrum, tech, and whatnot"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "light" # "dark", "auto", "light"
	customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.
  # mainSections = "post"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Articles"
url = "/posts"
weight = 2

[[menu.main]]
name = "Podcasts"
url = "/podcasts"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/ragozzine"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/johnragozzine/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
