name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: ragozzine/hugozzine@main
      env:
        TARGET_REPO: ragozzine/ragozzine.github.io
        TOKEN: ${{ secrets.TOKEN }}
        CNAME: www.ragozzine.me
